workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - when: never

stages:
  - build
  # - test

variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"

# .general: &general_config
#   before_script:
#     - pod install

build:
  stage: build
  # <<: *general_config
  tags:
    - job:build
  script:
    - xcodebuild clean -workspace iNASA.xcodeproj -scheme "Scheme debug"
    - xcodebuild build -workspace iNASA.xcodeproj -scheme "Scheme debug" -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
    - './scripts/youTrack.py "$CI_MERGE_REQUEST_TITLE" "Review"'

# test:
#   stage: test
#   <<: *general_config
#   tags: 
#     - job:test
#   script: 
#     - xcodebuild clean -workspace iNASA.xcodeproj -scheme " Scheme debug" | xcpretty
#     - xcodebuild test -workspace iNASA.xcodeproj -scheme ProjectTests -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
