name: CI/CD Pipeline

on:
  push:
    branches: 
    - '*'

jobs:
#  swiftLint:
#    name: SwiftLint

  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
#      - name: Install CocoaPods
#        run: pod install
          
      - name: Clean project
        run: xcodebuild -project iNASA.xcodeproj -scheme "iNASA" CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO" clean
        
      - name: Build project
        run: xcodebuild -project iNASA.xcodeproj -scheme "iNASA" -destination 'platform=iOS Simulator,name=iPhone 15,OS=17' CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO" build
        
      - name: Clean project
        run: xcodebuild -project iNASA.xcodeproj -scheme "iNASA" CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO" clean
        
      - name: Run Tests
        run: xcodebuild -project iNASA.xcodeproj -scheme "iNASATests" -destination 'platform=iOS Simulator,name=iPhone 15,OS=17' CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO" test
